#
# Module manifest for module 'Az.Network'
#
# Generated by: Microsoft Corporation
#
# Generated on: 6/30/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Az.Network.psm1'

# Version number of this module.
ModuleVersion = '4.18.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'f554cfcd-9cbb-4021-b158-fe20f0497f82'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - Networking service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.

For more information on Networking, please visit the following: https://docs.microsoft.com/azure/networking/networking-overview'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'AutoMapper.dll', 'Microsoft.Azure.Management.Network.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Network.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Add-AzApplicationGatewayAuthenticationCertificate', 
               'Get-AzApplicationGatewayAuthenticationCertificate', 
               'New-AzApplicationGatewayAuthenticationCertificate', 
               'Remove-AzApplicationGatewayAuthenticationCertificate', 
               'Set-AzApplicationGatewayAuthenticationCertificate', 
               'Get-AzApplicationGatewayAutoscaleConfiguration', 
               'New-AzApplicationGatewayAutoscaleConfiguration', 
               'Remove-AzApplicationGatewayAutoscaleConfiguration', 
               'Set-AzApplicationGatewayAutoscaleConfiguration', 
               'Get-AzApplicationGatewayAvailableWafRuleSet', 
               'Get-AzApplicationGatewayAvailableSslOption', 
               'Add-AzApplicationGatewayBackendAddressPool', 
               'Get-AzApplicationGatewayBackendAddressPool', 
               'New-AzApplicationGatewayBackendAddressPool', 
               'Remove-AzApplicationGatewayBackendAddressPool', 
               'Set-AzApplicationGatewayBackendAddressPool', 
               'Add-AzApplicationGatewayBackendHttpSetting', 
               'Get-AzApplicationGatewayBackendHttpSetting', 
               'New-AzApplicationGatewayBackendHttpSetting', 
               'Remove-AzApplicationGatewayBackendHttpSetting', 
               'Set-AzApplicationGatewayBackendHttpSetting', 
               'Get-AzApplicationGatewayConnectionDraining', 
               'New-AzApplicationGatewayConnectionDraining', 
               'Remove-AzApplicationGatewayConnectionDraining', 
               'Set-AzApplicationGatewayConnectionDraining', 
               'Get-AzApplicationGatewayWebApplicationFirewallConfiguration', 
               'New-AzApplicationGatewayWebApplicationFirewallConfiguration', 
               'Set-AzApplicationGatewayWebApplicationFirewallConfiguration', 
               'New-AzApplicationGatewayFirewallDisabledRuleGroupConfig', 
               'New-AzApplicationGatewayFirewallExclusionConfig', 
               'New-AzApplicationGatewayFirewallPolicyExclusionManagedRule', 
               'New-AzApplicationGatewayFirewallPolicyExclusionManagedRuleGroup', 
               'New-AzApplicationGatewayFirewallPolicyExclusionManagedRuleSet', 
               'New-AzApplicationGatewayFirewallCondition', 
               'New-AzApplicationGatewayFirewallCustomRule', 
               'New-AzApplicationGatewayFirewallMatchVariable', 
               'New-AzApplicationGatewayFirewallPolicy', 
               'Get-AzApplicationGatewayFirewallPolicy', 
               'Remove-AzApplicationGatewayFirewallPolicy', 
               'Set-AzApplicationGatewayFirewallPolicy', 
               'New-AzApplicationGatewayFirewallPolicyExclusion', 
               'New-AzApplicationGatewayFirewallPolicyManagedRule', 
               'New-AzApplicationGatewayFirewallPolicyManagedRuleOverride', 
               'New-AzApplicationGatewayFirewallPolicyManagedRuleGroupOverride', 
               'New-AzApplicationGatewayFirewallPolicyManagedRuleSet', 
               'New-AzApplicationGatewayFirewallPolicySetting', 
               'Add-AzApplicationGatewayFrontendIPConfig', 
               'Get-AzApplicationGatewayFrontendIPConfig', 
               'New-AzApplicationGatewayFrontendIPConfig', 
               'Remove-AzApplicationGatewayFrontendIPConfig', 
               'Set-AzApplicationGatewayFrontendIPConfig', 
               'Add-AzApplicationGatewayFrontendPort', 
               'Get-AzApplicationGatewayFrontendPort', 
               'New-AzApplicationGatewayFrontendPort', 
               'Remove-AzApplicationGatewayFrontendPort', 
               'Set-AzApplicationGatewayFrontendPort', 
               'Get-AzApplicationGatewayIdentity', 
               'New-AzApplicationGatewayIdentity', 
               'Remove-AzApplicationGatewayIdentity', 
               'Set-AzApplicationGatewayIdentity', 
               'Add-AzApplicationGatewayIPConfiguration', 
               'Get-AzApplicationGatewayIPConfiguration', 
               'New-AzApplicationGatewayIPConfiguration', 
               'Remove-AzApplicationGatewayIPConfiguration', 
               'Set-AzApplicationGatewayIPConfiguration', 
               'Get-AzApplicationGatewayBackendHealth', 'Get-AzApplicationGateway', 
               'Add-AzApplicationGatewayHttpListener', 
               'Get-AzApplicationGatewayHttpListener', 
               'New-AzApplicationGatewayHttpListener', 
               'Remove-AzApplicationGatewayHttpListener', 
               'Set-AzApplicationGatewayHttpListener', 'New-AzApplicationGateway', 
               'Add-AzApplicationGatewaySslProfile', 
               'Get-AzApplicationGatewaySslProfile', 
               'New-AzApplicationGatewaySslProfile', 
               'Remove-AzApplicationGatewaySslProfile', 
               'Set-AzApplicationGatewaySslProfile', 
               'New-AzApplicationGatewayCustomError', 
               'Add-AzApplicationGatewayCustomError', 
               'Get-AzApplicationGatewayCustomError', 
               'Remove-AzApplicationGatewayCustomError', 
               'Set-AzApplicationGatewayCustomError', 
               'Add-AzApplicationGatewayHttpListenerCustomError', 
               'Get-AzApplicationGatewayHttpListenerCustomError', 
               'Remove-AzApplicationGatewayHttpListenerCustomError', 
               'Set-AzApplicationGatewayHttpListenerCustomError', 
               'New-AzApplicationGatewayPathRuleConfig', 
               'Add-AzApplicationGatewayProbeConfig', 
               'Get-AzApplicationGatewayProbeConfig', 
               'New-AzApplicationGatewayProbeConfig', 
               'Remove-AzApplicationGatewayProbeConfig', 
               'Set-AzApplicationGatewayProbeConfig', 
               'New-AzApplicationGatewayProbeHealthResponseMatch', 
               'Remove-AzApplicationGateway', 
               'Add-AzApplicationGatewayRequestRoutingRule', 
               'Get-AzApplicationGatewayRequestRoutingRule', 
               'New-AzApplicationGatewayRequestRoutingRule', 
               'Remove-AzApplicationGatewayRequestRoutingRule', 
               'Set-AzApplicationGatewayRequestRoutingRule', 
               'Add-AzApplicationGatewayRewriteRuleSet', 
               'Get-AzApplicationGatewayRewriteRuleSet', 
               'New-AzApplicationGatewayRewriteRuleSet', 
               'Remove-AzApplicationGatewayRewriteRuleSet', 
               'Set-AzApplicationGatewayRewriteRuleSet', 
               'New-AzApplicationGatewayRewriteRule', 
               'New-AzApplicationGatewayRewriteRuleActionSet', 
               'New-AzApplicationGatewayRewriteRuleHeaderConfiguration', 
               'New-AzApplicationGatewayRewriteRuleUrlConfiguration', 
               'Get-AzApplicationGatewayAvailableServerVariableAndHeader', 
               'New-AzApplicationGatewayRewriteRuleCondition', 
               'Add-AzApplicationGatewayRedirectConfiguration', 
               'Get-AzApplicationGatewayRedirectConfiguration', 
               'New-AzApplicationGatewayRedirectConfiguration', 
               'Remove-AzApplicationGatewayRedirectConfiguration', 
               'Set-AzApplicationGatewayRedirectConfiguration', 
               'Set-AzApplicationGateway', 'Get-AzApplicationGatewaySku', 
               'New-AzApplicationGatewaySku', 'Set-AzApplicationGatewaySku', 
               'Add-AzApplicationGatewaySslCertificate', 
               'Get-AzApplicationGatewaySslCertificate', 
               'New-AzApplicationGatewaySslCertificate', 
               'Remove-AzApplicationGatewaySslCertificate', 
               'Set-AzApplicationGatewaySslCertificate', 
               'Get-AzApplicationGatewaySslPolicy', 
               'New-AzApplicationGatewaySslPolicy', 
               'Remove-AzApplicationGatewaySslPolicy', 
               'Set-AzApplicationGatewaySslPolicy', 
               'Get-AzApplicationGatewaySslProfilePolicy', 
               'Remove-AzApplicationGatewaySslProfilePolicy', 
               'Set-AzApplicationGatewaySslProfilePolicy', 
               'Get-AzApplicationGatewayClientAuthConfiguration', 
               'New-AzApplicationGatewayClientAuthConfiguration', 
               'Remove-AzApplicationGatewayClientAuthConfiguration', 
               'Set-AzApplicationGatewayClientAuthConfiguration', 
               'Get-AzApplicationGatewaySslPredefinedPolicy', 
               'Start-AzApplicationGateway', 'Stop-AzApplicationGateway', 
               'Add-AzApplicationGatewayTrustedRootCertificate', 
               'Get-AzApplicationGatewayTrustedRootCertificate', 
               'New-AzApplicationGatewayTrustedRootCertificate', 
               'Remove-AzApplicationGatewayTrustedRootCertificate', 
               'Set-AzApplicationGatewayTrustedRootCertificate', 
               'Add-AzApplicationGatewayTrustedClientCertificate', 
               'Get-AzApplicationGatewayTrustedClientCertificate', 
               'New-AzApplicationGatewayTrustedClientCertificate', 
               'Remove-AzApplicationGatewayTrustedClientCertificate', 
               'Set-AzApplicationGatewayTrustedClientCertificate', 
               'Add-AzApplicationGatewayUrlPathMapConfig', 
               'Get-AzApplicationGatewayUrlPathMapConfig', 
               'New-AzApplicationGatewayUrlPathMapConfig', 
               'Remove-AzApplicationGatewayUrlPathMapConfig', 
               'Set-AzApplicationGatewayUrlPathMapConfig', 
               'New-AzApplicationGatewayPrivateLinkConfiguration', 
               'Add-AzApplicationGatewayPrivateLinkConfiguration', 
               'Set-AzApplicationGatewayPrivateLinkConfiguration', 
               'Get-AzApplicationGatewayPrivateLinkConfiguration', 
               'Remove-AzApplicationGatewayPrivateLinkConfiguration', 
               'New-AzApplicationGatewayPrivateLinkIpConfiguration', 
               'Add-AzExpressRouteCircuitAuthorization', 
               'Get-AzExpressRouteCircuitAuthorization', 
               'New-AzExpressRouteCircuitAuthorization', 
               'Remove-AzExpressRouteCircuitAuthorization', 
               'Move-AzExpressRouteCircuit', 'Get-AzExpressRouteCircuitARPTable', 
               'Get-AzExpressRouteCircuitRouteTable', 
               'Get-AzExpressRouteCircuitRouteTableSummary', 
               'Get-AzExpressRouteCircuitStat', 
               'Add-AzLoadBalancerInboundNatPoolConfig', 
               'Get-AzLoadBalancerInboundNatPoolConfig', 
               'New-AzLoadBalancerInboundNatPoolConfig', 
               'Remove-AzLoadBalancerInboundNatPoolConfig', 
               'Set-AzLoadBalancerInboundNatPoolConfig', 
               'Get-AzExpressRouteCircuit', 'New-AzExpressRouteCircuit', 
               'Add-AzExpressRouteCircuitPeeringConfig', 
               'Get-AzExpressRouteCircuitPeeringConfig', 
               'New-AzExpressRouteCircuitPeeringConfig', 
               'Remove-AzExpressRouteCircuitPeeringConfig', 
               'Set-AzExpressRouteCircuitPeeringConfig', 
               'Remove-AzExpressRouteCircuit', 'Set-AzExpressRouteCircuit', 
               'Get-AzExpressRoutePort', 'New-AzExpressRoutePort', 
               'Get-AzExpressRoutePortLinkConfig', 'Remove-AzExpressRoutePort', 
               'Set-AzExpressRoutePort', 'Get-AzExpressRoutePortsLocation', 
               'Get-AzExpressRoutePortIdentity', 'New-AzExpressRoutePortIdentity', 
               'Remove-AzExpressRoutePortIdentity', 
               'Set-AzExpressRoutePortIdentity', 
               'Add-AzExpressRoutePortAuthorization', 
               'Get-AzExpressRoutePortAuthorization', 
               'Remove-AzExpressRoutePortAuthorization', 
               'Get-AzEffectiveNetworkSecurityGroup', 'Get-AzEffectiveRouteTable', 
               'Add-AzNetworkInterfaceIpConfig', 'Get-AzNetworkInterfaceIpConfig', 
               'New-AzNetworkInterfaceIpConfig', 
               'Remove-AzNetworkInterfaceIpConfig', 
               'Set-AzNetworkInterfaceIpConfig', 'New-AzNetworkWatcher', 
               'Get-AzNetworkWatcher', 'Remove-AzNetworkWatcher', 
               'New-AzNetworkWatcherPacketCapture', 
               'Get-AzNetworkWatcherPacketCapture', 
               'Stop-AzNetworkWatcherPacketCapture', 
               'Remove-AzNetworkWatcherPacketCapture', 
               'New-AzPacketCaptureFilterConfig', 'Get-AzNetworkWatcherTopology', 
               'Get-AzNetworkWatcherSecurityGroupView', 
               'Test-AzNetworkWatcherIPFlow', 'Get-AzNetworkWatcherNextHop', 
               'Start-AzNetworkWatcherResourceTroubleshooting', 
               'Get-AzNetworkWatcherTroubleshootingResult', 
               'Get-AzNetworkWatcherFlowLogStatus', 
               'Set-AzNetworkWatcherConfigFlowLog', 'New-AzNetworkWatcherFlowLog', 
               'Set-AzNetworkWatcherFlowLog', 'Get-AzNetworkWatcherFlowLog', 
               'Remove-AzNetworkWatcherFlowLog', 
               'Test-AzNetworkWatcherConnectivity', 
               'Get-AzNetworkWatcherReachabilityReport', 
               'Get-AzNetworkWatcherReachabilityProvidersList', 
               'New-AzNetworkWatcherConnectionMonitorEndpointObject', 
               'New-AzNetworkWatcherConnectionMonitorObject', 
               'New-AzNetworkWatcherConnectionMonitorEndpointScopeItemObject', 
               'New-AzNetworkWatcherConnectionMonitorTestConfigurationObject', 
               'New-AzNetworkWatcherConnectionMonitorTestGroupObject', 
               'New-AzNetworkWatcherConnectionMonitorOutputObject', 
               'New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject', 
               'New-AzNetworkWatcherConnectionMonitor', 
               'Set-AzNetworkWatcherConnectionMonitor', 
               'Start-AzNetworkWatcherConnectionMonitor', 
               'Stop-AzNetworkWatcherConnectionMonitor', 
               'Remove-AzNetworkWatcherConnectionMonitor', 
               'Get-AzNetworkWatcherConnectionMonitor', 
               'Get-AzNetworkWatcherConnectionMonitorReport', 
               'Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic', 
               'New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile', 
               'Get-AzExpressRouteServiceProvider', 
               'Test-AzPrivateIPAddressAvailability', 'Get-AzPublicIpAddress', 
               'New-AzPublicIpAddress', 'Remove-AzPublicIpAddress', 
               'Set-AzPublicIpAddress', 'Get-AzPublicIpPrefix', 
               'New-AzPublicIpPrefix', 'Remove-AzPublicIpPrefix', 
               'Set-AzPublicIpPrefix', 'Get-AzRouteTable', 'New-AzRouteTable', 
               'Remove-AzRouteTable', 'Add-AzRouteConfig', 'Get-AzRouteConfig', 
               'New-AzRouteConfig', 'Remove-AzRouteConfig', 'Set-AzRouteConfig', 
               'Set-AzRouteTable', 'New-AzRadiusServer', 
               'Set-AzVirtualNetworkGateway', 'Get-AzVirtualNetworkGateway', 
               'New-AzVirtualNetworkGateway', 
               'Get-AzVirtualNetworkGatewayVpnclientConnectionHealth', 
               'Get-AzVpnClientRootCertificate', 
               'Get-AzVpnClientRevokedCertificate', 
               'Add-AzVpnClientRootCertificate', 
               'Add-AzVpnClientRevokedCertificate', 
               'New-AzVpnClientRootCertificate', 
               'New-AzVpnClientRevokedCertificate', 
               'Resize-AzVirtualNetworkGateway', 
               'Remove-AzVpnClientRevokedCertificate', 
               'Remove-AzVpnClientRootCertificate', 'Get-AzVpnClientPackage', 
               'New-AzVpnClientConfiguration', 'Get-AzVpnClientConfiguration', 
               'New-AzVirtualNetworkGatewayIpConfig', 
               'Add-AzVirtualNetworkGatewayIpConfig', 
               'Remove-AzVirtualNetworkGatewayIpConfig', 
               'Remove-AzVirtualNetworkGateway', 'Reset-AzVirtualNetworkGateway', 
               'Set-AzVirtualNetworkGatewayDefaultSite', 
               'Remove-AzVirtualNetworkGatewayDefaultSite', 
               'New-AzVpnClientIpsecPolicy', 'New-AzVpnClientIpsecParameter', 
               'Set-AzVpnClientIpsecParameter', 'Get-AzVpnClientIpsecParameter', 
               'Remove-AzVpnClientIpsecParameter', 'Remove-AzLocalNetworkGateway', 
               'Get-AzLocalNetworkGateway', 'New-AzLocalNetworkGateway', 
               'Set-AzLocalNetworkGateway', 
               'Get-AzVirtualNetworkGatewayConnection', 
               'Get-AzVirtualNetworkGatewayConnectionIkeSa', 
               'Reset-AzVirtualNetworkGatewayConnection', 
               'Get-AzVirtualNetworkGatewayConnectionSharedKey', 
               'New-AzVirtualNetworkGatewayConnection', 
               'Remove-AzVirtualNetworkGatewayConnection', 
               'Reset-AzVirtualNetworkGatewayConnectionSharedKey', 
               'Set-AzVirtualNetworkGatewayConnectionSharedKey', 
               'Set-AzVirtualNetworkGatewayConnection', 'New-AzIpsecPolicy', 
               'New-AzIpsecTrafficSelectorPolicy', 
               'Get-AzLoadBalancerBackendAddressPool', 
               'New-AzLoadBalancerBackendAddressPool', 
               'Remove-AzLoadBalancerBackendAddressPool', 
               'Set-AzLoadBalancerBackendAddressPool', 
               'New-AzLoadBalancerBackendAddressPoolTunnelInterfaceConfig', 
               'New-AzLoadBalancerBackendAddressConfig', 
               'Get-AzLoadBalancerBackendAddressPoolConfig', 
               'Add-AzLoadBalancerBackendAddressPoolConfig', 
               'New-AzLoadBalancerBackendAddressPoolConfig', 
               'Remove-AzLoadBalancerBackendAddressPoolConfig', 
               'Get-AzLoadBalancerBackendAddressInboundNatRulePortMapping', 
               'Set-AzLoadBalancerFrontendIpConfig', 
               'Get-AzLoadBalancerFrontendIpConfig', 
               'Add-AzLoadBalancerFrontendIpConfig', 
               'New-AzLoadBalancerFrontendIpConfig', 
               'Remove-AzLoadBalancerFrontendIpConfig', 'Get-AzLoadBalancer', 
               'Set-AzLoadBalancerInboundNatRuleConfig', 
               'Get-AzLoadBalancerInboundNatRuleConfig', 
               'Add-AzLoadBalancerInboundNatRuleConfig', 
               'New-AzLoadBalancerInboundNatRuleConfig', 
               'Remove-AzLoadBalancerInboundNatRuleConfig', 
               'Get-AzBgpServiceCommunity', 'Get-AzRouteFilter', 'Set-AzRouteFilter', 
               'Remove-AzRouteFilter', 'New-AzRouteFilter', 
               'Get-AzRouteFilterRuleConfig', 'Add-AzRouteFilterRuleConfig', 
               'Remove-AzRouteFilterRuleConfig', 'Set-AzRouteFilterRuleConfig', 
               'New-AzRouteFilterRuleConfig', 'Set-AzLoadBalancerRuleConfig', 
               'Get-AzLoadBalancerRuleConfig', 'Add-AzLoadBalancerRuleConfig', 
               'New-AzLoadBalancerRuleConfig', 'Remove-AzLoadBalancerRuleConfig', 
               'New-AzLoadBalancer', 'Set-AzLoadBalancerProbeConfig', 
               'Get-AzLoadBalancerProbeConfig', 'Add-AzLoadBalancerProbeConfig', 
               'New-AzLoadBalancerProbeConfig', 'Remove-AzLoadBalancerProbeConfig', 
               'Remove-AzLoadBalancer', 'Set-AzLoadBalancer', 
               'Add-AzLoadBalancerOutboundRuleConfig', 
               'Get-AzLoadBalancerOutboundRuleConfig', 
               'New-AzLoadBalancerOutboundRuleConfig', 
               'Set-AzLoadBalancerOutboundRuleConfig', 
               'Remove-AzLoadBalancerOutboundRuleConfig', 
               'Remove-AzNetworkInterface', 'Get-AzNetworkInterface', 
               'New-AzNetworkInterface', 'Set-AzNetworkInterface', 
               'Get-AzNetworkSecurityGroup', 'New-AzNetworkSecurityRuleConfig', 
               'Get-AzNetworkSecurityRuleConfig', 
               'Remove-AzNetworkSecurityRuleConfig', 
               'Set-AzNetworkSecurityRuleConfig', 
               'Add-AzNetworkSecurityRuleConfig', 'New-AzNetworkSecurityGroup', 
               'Remove-AzNetworkSecurityGroup', 'Set-AzNetworkSecurityGroup', 
               'Test-AzDnsAvailability', 'Add-AzVirtualNetworkPeering', 
               'Get-AzVirtualNetworkPeering', 'Remove-AzVirtualNetworkPeering', 
               'Set-AzVirtualNetworkPeering', 'Sync-AzVirtualNetworkPeering', 
               'Remove-AzVirtualNetwork', 'Set-AzVirtualNetwork', 
               'Remove-AzVirtualNetworkSubnetConfig', 
               'Set-AzVirtualNetworkSubnetConfig', 
               'Get-AzVirtualNetworkSubnetConfig', 
               'Add-AzVirtualNetworkSubnetConfig', 
               'New-AzVirtualNetworkSubnetConfig', 'New-AzDelegation', 
               'Add-AzDelegation', 'Get-AzDelegation', 'Remove-AzDelegation', 
               'Get-AzAvailableServiceDelegation', 'Get-AzVirtualNetwork', 
               'New-AzVirtualNetwork', 'Get-AzVirtualNetworkGatewayBgpPeerStatus', 
               'Get-AzVirtualNetworkGatewayAdvertisedRoute', 
               'Get-AzVirtualNetworkGatewayLearnedRoute', 'Get-AzNetworkUsage', 
               'Get-AzVirtualNetworkUsageList', 
               'Get-AzVirtualNetworkAvailableEndpointService', 
               'Get-AzVirtualNetworkGatewaySupportedVpnDevice', 
               'Get-AzVirtualNetworkGatewayConnectionVpnDeviceConfigScript', 
               'New-AzApplicationSecurityGroup', 
               'Remove-AzApplicationSecurityGroup', 
               'Get-AzApplicationSecurityGroup', 'New-AzPublicIpTag', 
               'New-AzDdosProtectionPlan', 'Get-AzDdosProtectionPlan', 
               'Remove-AzDdosProtectionPlan', 
               'New-AzNetworkWatcherProtocolConfiguration', 
               'Add-AzExpressRouteCircuitConnectionConfig', 
               'Set-AzExpressRouteCircuitConnectionConfig', 
               'Get-AzExpressRouteCircuitConnectionConfig', 
               'Remove-AzExpressRouteCircuitConnectionConfig', 
               'New-AzServiceEndpointPolicy', 'Remove-AzServiceEndpointPolicy', 
               'Get-AzServiceEndpointPolicy', 
               'New-AzServiceEndpointPolicyDefinition', 
               'Remove-AzServiceEndpointPolicyDefinition', 
               'Get-AzServiceEndpointPolicyDefinition', 
               'Set-AzServiceEndpointPolicyDefinition', 
               'Add-AzServiceEndpointPolicyDefinition', 
               'Set-AzServiceEndpointPolicy', 'New-AzVirtualWan', 
               'Update-AzVirtualWan', 'Get-AzVirtualWan', 'Remove-AzVirtualWan', 
               'Get-AzVirtualWanVpnServerConfiguration', 
               'Get-AzVirtualWanVpnServerConfigurationVpnProfile', 
               'New-AzVirtualHub', 'Get-AzVirtualHub', 'Update-AzVirtualHub', 
               'Remove-AzVirtualHub', 'Set-AzVirtualHub', 'New-AzVirtualHubRoute', 
               'Add-AzVirtualHubRoute', 'New-AzVirtualHubRouteTable', 
               'Add-AzVirtualHubRouteTable', 'Get-AzVirtualHubRouteTable', 
               'Remove-AzVirtualHubRouteTable', 'New-AzVpnGateway', 
               'Reset-AzVpnGateway', 'Get-AzVpnGateway', 'Update-AzVpnGateway', 
               'Remove-AzVpnGateway', 'Start-AzVpnGatewayPacketCapture', 
               'Stop-AzVpnGatewayPacketCapture', 'New-AzVpnGatewayNatRule', 
               'Update-AzVpnGatewayNatRule', 'Remove-AzVpnGatewayNatRule', 
               'Get-AzVpnGatewayNatRule', 'Start-AzVpnConnectionPacketCapture', 
               'Stop-AzVpnConnectionPacketCapture', 'New-AzVpnSite', 
               'New-AzVpnSiteLink', 'New-AzVpnSiteLinkConnection', 'Get-AzVpnSite', 
               'Reset-AzVpnSiteLinkConnection', 'Get-AzVpnSiteLinkConnectionIkeSa', 
               'Update-AzVpnSite', 'Remove-AzVpnSite', 'New-AzVpnConnection', 
               'Get-AzVpnConnection', 'Update-AzVpnConnection', 
               'Remove-AzVpnConnection', 'New-AzVirtualHubVnetConnection', 
               'Get-AzVirtualHubVnetConnection', 
               'Remove-AzVirtualHubVnetConnection', 
               'Update-AzVirtualHubVnetConnection', 'Get-AzVpnServerConfiguration', 
               'New-AzVpnServerConfiguration', 'Remove-AzVpnServerConfiguration', 
               'Update-AzVpnServerConfiguration', 
               'Get-AzVpnServerConfigurationPolicyGroup', 
               'New-AzVpnServerConfigurationPolicyGroup', 
               'Remove-AzVpnServerConfigurationPolicyGroup', 
               'Update-AzVpnServerConfigurationPolicyGroup', 'Get-AzP2sVpnGateway', 
               'Disconnect-AzP2sVpnGatewayVpnConnection', 
               'Get-AzP2sVpnGatewayConnectionHealth', 
               'Get-AzP2sVpnGatewayDetailedConnectionHealth', 
               'Get-AzP2sVpnGatewayVpnProfile', 'New-AzP2sVpnGateway', 
               'Remove-AzP2sVpnGateway', 'Update-AzP2sVpnGateway', 
               'Reset-AzP2sVpnGateway', 'Get-AzVirtualWanVpnConfiguration', 
               'Get-AzFirewall', 'Set-AzFirewall', 'New-AzFirewall', 
               'Remove-AzFirewall', 'New-AzFirewallApplicationRuleCollection', 
               'New-AzFirewallApplicationRule', 'New-AzFirewallNatRuleCollection', 
               'New-AzFirewallNatRule', 'New-AzFirewallNetworkRuleCollection', 
               'New-AzFirewallNetworkRule', 'New-AzFirewallThreatIntelWhitelist', 
               'New-AzFirewallHubPublicIpAddress', 'New-AzFirewallHubIpAddress', 
               'New-AzFirewallPublicIpAddress', 'Get-AzFirewallFqdnTag', 
               'Get-AzNetworkProfile', 'New-AzNetworkProfile', 
               'Remove-AzNetworkProfile', 'Set-AzNetworkProfile', 
               'New-AzContainerNicConfig', 'New-AzContainerNicConfigIpConfig', 
               'Add-AzNetworkInterfaceTapConfig', 
               'Get-AzNetworkInterfaceTapConfig', 
               'Set-AzNetworkInterfaceTapConfig', 
               'Remove-AzNetworkInterfaceTapConfig', 'Get-AzVirtualNetworkTap', 
               'New-AzVirtualNetworkTap', 'Remove-AzVirtualNetworkTap', 
               'Set-AzVirtualNetworkTap', 'Get-AzExpressRouteGateway', 
               'New-AzExpressRouteGateway', 'Remove-AzExpressRouteGateway', 
               'Set-AzExpressRouteGateway', 'Get-AzExpressRouteConnection', 
               'New-AzExpressRouteConnection', 'Remove-AzExpressRouteConnection', 
               'Set-AzExpressRouteConnection', 'Get-AzExpressRouteCrossConnection', 
               'Set-AzExpressRouteCrossConnection', 
               'Add-AzExpressRouteCrossConnectionPeering', 
               'Get-AzExpressRouteCrossConnectionPeering', 
               'Remove-AzExpressRouteCrossConnectionPeering', 
               'Get-AzExpressRouteCrossConnectionArpTable', 
               'Get-AzExpressRouteCrossConnectionRouteTable', 
               'Get-AzExpressRouteCrossConnectionRouteTableSummary', 
               'Get-AzNatGateway', 'New-AzNatGateway', 'Remove-AzNatGateway', 
               'Set-AzNatGateway', 'Get-AzNetworkServiceTag', 
               'New-AzPrivateEndpoint', 'Get-AzPrivateEndpoint', 
               'Remove-AzPrivateEndpoint', 'New-AzPrivateLinkServiceConnection', 
               'New-AzPrivateDnsZoneConfig', 'Remove-AzPrivateDnsZoneGroup', 
               'Get-AzPrivateDnsZoneGroup', 'New-AzPrivateDnsZoneGroup', 
               'Set-AzPrivateDnsZoneGroup', 'New-AzPrivateLinkService', 
               'Get-AzPrivateLinkService', 'Remove-AzPrivateLinkService', 
               'New-AzPrivateLinkServiceIpConfig', 'Set-AzPrivateEndpoint', 
               'Set-AzPrivateLinkService', 'Set-AzPrivateEndpointConnection', 
               'Get-AzPrivateEndpointConnection', 
               'Remove-AzPrivateEndpointConnection', 
               'Get-AzAutoApprovedPrivateLinkService', 
               'Test-AzPrivateLinkServiceVisibility', 
               'Approve-AzPrivateEndpointConnection', 
               'Deny-AzPrivateEndpointConnection', 
               'Get-AzAvailablePrivateEndpointType', 'Get-AzAvailableServiceAlias', 
               'Get-AzPrivateLinkResource', 'New-AzBastion', 'Get-AzBastion', 
               'Remove-AzBastion', 'Set-AzBastion', 
               'Start-AzVirtualNetworkGatewayPacketCapture', 
               'Stop-AzVirtualNetworkGatewayPacketCapture', 
               'Start-AzVirtualNetworkGatewayConnectionPacketCapture', 
               'Stop-AzVirtualNetworkGatewayConnectionPacketCapture', 
               'Disconnect-AzVirtualNetworkGatewayVpnConnection', 
               'New-AzFirewallPolicyNetworkRule', 'New-AzFirewallPolicyNatRule', 
               'New-AzFirewallPolicyApplicationRule', 
               'New-AzFirewallPolicyNatRuleCollection', 
               'New-AzFirewallPolicyFilterRuleCollection', 
               'New-AzFirewallPolicyRuleCollectionGroup', 
               'Set-AzFirewallPolicyRuleCollectionGroup', 
               'Get-AzFirewallPolicyRuleCollectionGroup', 
               'Remove-AzFirewallPolicyRuleCollectionGroup', 
               'New-AzFirewallPolicy', 'Get-AzFirewallPolicy', 
               'Set-AzFirewallPolicy', 'Remove-AzFirewallPolicy', 
               'New-AzFirewallPolicyIntrusionDetection', 
               'New-AzFirewallPolicyIntrusionDetectionBypassTraffic', 
               'New-AzFirewallPolicyIntrusionDetectionSignatureOverride', 
               'New-AzFirewallPolicyThreatIntelWhitelist', 
               'New-AzFirewallPolicyDnsSetting', 'New-AzFirewallPolicySqlSetting', 
               'New-AzVirtualRouter', 'Remove-AzVirtualRouter', 
               'Get-AzVirtualRouter', 'Update-AzVirtualRouter', 
               'Add-AzVirtualRouterPeer', 'Update-AzVirtualRouterPeer', 
               'Remove-AzVirtualRouterPeer', 'Get-AzVirtualRouterPeer', 
               'Get-AzVirtualRouterPeerAdvertisedRoute', 
               'Get-AzVirtualRouterPeerLearnedRoute', 'New-AzRouteServer', 
               'Remove-AzRouteServer', 'Get-AzRouteServer', 'Update-AzRouteServer', 
               'Add-AzRouteServerPeer', 'Update-AzRouteServerPeer', 
               'Remove-AzRouteServerPeer', 'Get-AzRouteServerPeer', 
               'Get-AzRouteServerPeerAdvertisedRoute', 
               'Get-AzRouteServerPeerLearnedRoute', 'New-AzIpGroup', 
               'Remove-AzIpGroup', 'Get-AzIpGroup', 'Set-AzIpGroup', 
               'New-AzIpConfigurationBgpPeeringAddressObject', 
               'New-AzIpAllocation', 'Get-AzIpAllocation', 'Remove-AzIpAllocation', 
               'Set-AzIpAllocation', 'New-AzSecurityPartnerProvider', 
               'Remove-AzSecurityPartnerProvider', 'Get-AzSecurityPartnerProvider', 
               'Set-AzSecurityPartnerProvider', 'Reset-AzHubRouter', 
               'New-AzVHubRoute', 'New-AzStaticRoute', 'New-AzRoutingConfiguration', 
               'New-AzVHubRouteTable', 'Get-AzVHubRouteTable', 
               'Update-AzVHubRouteTable', 'Remove-AzVHubRouteTable', 
               'Get-AzNetworkVirtualAppliance', 'New-AzNetworkVirtualAppliance', 
               'Remove-AzNetworkVirtualAppliance', 
               'Update-AzNetworkVirtualAppliance', 'Get-AzVirtualApplianceSite', 
               'New-AzVirtualApplianceSite', 'Remove-AzVirtualApplianceSite', 
               'Update-AzVirtualApplianceSite', 'New-AzOffice365PolicyProperty', 
               'Get-AzNetworkVirtualApplianceSku', 
               'New-AzVirtualApplianceSkuProperty', 'New-AzCustomIpPrefix', 
               'Update-AzCustomIpPrefix', 'Get-AzCustomIpPrefix', 
               'Remove-AzCustomIpPrefix', 'New-AzExpressRoutePortLOA', 
               'New-AzO365PolicyProperty', 'Get-AzVirtualNetworkGatewayNatRule', 
               'New-AzVirtualNetworkGatewayNatRule', 
               'Update-AzVirtualNetworkGatewayNatRule', 
               'Remove-AzVirtualNetworkGatewayNatRule', 
               'Get-AzVirtualHubBgpConnection', 'New-AzVirtualHubBgpConnection', 
               'Remove-AzVirtualHubBgpConnection', 
               'Update-AzVirtualHubBgpConnection', 
               'New-AzPrivateEndpointIpConfiguration'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'List-AzApplicationGatewayAvailableWafRuleSets', 
               'List-AzApplicationGatewayAvailableSslOptions', 
               'List-AzApplicationGatewaySslPredefinedPolicy', 
               'List-AzApplicationGatewayAvailableServerVariableAndHeader', 
               'Add-AzApplicationGatewayBackendHttpSettings', 
               'Get-AzApplicationGatewayBackendHttpSettings', 
               'New-AzApplicationGatewayBackendHttpSettings', 
               'Remove-AzApplicationGatewayBackendHttpSettings', 
               'Set-AzApplicationGatewayBackendHttpSettings', 
               'Get-AzExpressRouteCircuitStats', 
               'Get-AzApplicationGatewayAvailableWafRuleSets', 
               'Get-AzApplicationGatewayAvailableSslOptions', 
               'Get-AzInterfaceEndpoint', 
               'New-AzFirewallThreatIntelWhitelistObject'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ResourceManager','ARM','Network','VirtualNetwork'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* Added support for CustomV2 ssl policies for Application Gateway.
    - Added ''CustomV2'' to the validation set of ''PolicyType''
    - Added ''TLSv1_3'' to the validation set of ''MinProtocolVersion''
    - Removed validation for null or empty cipher suites list since there can be empty cipher suites list for min protocol version of tls1.3
* [Breaking Change] Changed default value of ''-PrivateEndpointNetworkPoliciesFlag'' to ''Disabled'' in ''Add-AzVirtualNetworkSubnetConfig'' and ''New-AzVirtualNetworkSubnetConfig''
* Fixed bugs that cannot parse virtual network encryption paramemters when updating exsiting vnet.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInogYJKoZIhvcNAQcCoIInkzCCJ48CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCA7t7OU9yDGMuXL
# QZO+XA18jxQqMZs2GAR0w+vk+7/CsaCCDYUwggYDMIID66ADAgECAhMzAAACU+OD
# 3pbexW7MAAAAAAJTMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjEwOTAyMTgzMzAwWhcNMjIwOTAxMTgzMzAwWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDLhxHwq3OhH+4J+SX4qS/VQG8HybccH7tnG+BUqrXubfGuDFYPZ29uCuHfQlO1
# lygLgMpJ4Geh6/6poQ5VkDKfVssn6aA1PCzIh8iOPMQ9Mju3sLF9Sn+Pzuaie4BN
# rp0MuZLDEXgVYx2WNjmzqcxC7dY9SC3znOh5qUy2vnmWygC7b9kj0d3JrGtjc5q5
# 0WfV3WLXAQHkeRROsJFBZfXFGoSvRljFFUAjU/zdhP92P+1JiRRRikVy/sqIhMDY
# +7tVdzlE2fwnKOv9LShgKeyEevgMl0B1Fq7E2YeBZKF6KlhmYi9CE1350cnTUoU4
# YpQSnZo0YAnaenREDLfFGKTdAgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUlZpLWIccXoxessA/DRbe26glhEMw
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzQ2NzU5ODAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# AKVY+yKcJVVxf9W2vNkL5ufjOpqcvVOOOdVyjy1dmsO4O8khWhqrecdVZp09adOZ
# 8kcMtQ0U+oKx484Jg11cc4Ck0FyOBnp+YIFbOxYCqzaqMcaRAgy48n1tbz/EFYiF
# zJmMiGnlgWFCStONPvQOBD2y/Ej3qBRnGy9EZS1EDlRN/8l5Rs3HX2lZhd9WuukR
# bUk83U99TPJyo12cU0Mb3n1HJv/JZpwSyqb3O0o4HExVJSkwN1m42fSVIVtXVVSa
# YZiVpv32GoD/dyAS/gyplfR6FI3RnCOomzlycSqoz0zBCPFiCMhVhQ6qn+J0GhgR
# BJvGKizw+5lTfnBFoqKZJDROz+uGDl9tw6JvnVqAZKGrWv/CsYaegaPePFrAVSxA
# yUwOFTkAqtNC8uAee+rv2V5xLw8FfpKJ5yKiMKnCKrIaFQDr5AZ7f2ejGGDf+8Tz
# OiK1AgBvOW3iTEEa/at8Z4+s1CmnEAkAi0cLjB72CJedU1LAswdOCWM2MDIZVo9j
# 0T74OkJLTjPd3WNEyw0rBXTyhlbYQsYt7ElT2l2TTlF5EmpVixGtj4ChNjWoKr9y
# TAqtadd2Ym5FNB792GzwNwa631BPCgBJmcRpFKXt0VEQq7UXVNYBiBRd+x4yvjqq
# 5aF7XC5nXCgjbCk7IXwmOphNuNDNiRq83Ejjnc7mxrJGMIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGXMwghlvAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAAJT44Pelt7FbswAAAAA
# AlMwDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIL+v
# v5lC5ctsYgHjnDuA1Qpy7ppFefFtt+qaaoMsHL22MEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAbvqHC/VrEkoycegitZ/bj317C1AG38z9LvCA
# Z+GB2jq1qnXS75/1m9yIsvWm4YvT5ydVOZJHoLZ1SLmT3Ozz5eijty8VWW+Adm4w
# 3SjEhLUJoJ/4KbnhZ/45j0VUHy7N3oXJfrDmA1g6LA7GENAOIVvXB92DcWA90yIe
# 7xAQLO0JAjhnWRMQYWeKNNX2impfq2LFAPavHRdMZTJ3PbUUyk/WnPDHLNqkeSRJ
# 04H8hrQn1RuPEb9UyBTGSrsXIQDgMymJwc1y/NzWWR9TPltpjcbYHiFNKvDkfFSA
# 4bDdr9NxIppZOeVDfZl/VCBxzPCNb3mAAH0Ey4Id4Y9FIIzu9KGCFv0wghb5Bgor
# BgEEAYI3AwMBMYIW6TCCFuUGCSqGSIb3DQEHAqCCFtYwghbSAgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFRBgsqhkiG9w0BCRABBKCCAUAEggE8MIIBOAIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCC2+Ex5p69ExPoNgU5n9l/O3Y5wOQQRgzTj
# lQHCYMpIqgIGYrSvFWkHGBMyMDIyMDYzMDEwMjcwNy44OTRaMASAAgH0oIHQpIHN
# MIHKMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQL
# ExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMSYwJAYDVQQLEx1UaGFsZXMg
# VFNTIEVTTjpBRTJDLUUzMkItMUFGQzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgU2VydmljZaCCEVQwggcMMIIE9KADAgECAhMzAAABlklbYuEv3fdPAAEA
# AAGWMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
# MB4XDTIxMTIwMjE5MDUxM1oXDTIzMDIyODE5MDUxM1owgcoxCzAJBgNVBAYTAlVT
# MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVy
# aWNhIE9wZXJhdGlvbnMxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNOOkFFMkMtRTMy
# Qi0xQUZDMSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIIC
# IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0h9sEAtvrf48wOoy+i2TIQzS
# RtJ79XFKnvh+DBishIEWVMKdWLB5dSExsovCva5D0SiigItJU/ING9RiIqZFnPKg
# rRN8Im8aDUeJgsq74BLF7rZ28SNaG8fHDH2tl4HIRv1wRmXBbRndFEL15MVGL6JH
# xtU8gTKpyGb0Ni7XJho/OpWj0TbkaHZBDO1VVDtqDEhyW2kzY9W9pAAvLKpcrR9c
# 5n60KUwN62TshJssE+Nw0X7DZV5pDSjIluwWnzZx2SxhxmnKYphOHaAzLq98oh/6
# ggsdjzuKSKpAOlixkjfMoWGr3EGURVbbJf8fyIri9H8TxqUJkXPOJuNcmrp3L3jY
# f+f9eDKrGe7oGNYsfH5DmICQZS7LPJsj4WjAOqnBAf0VlqnAn4cgETYwnJgTRjV3
# jICsmf/nt2wjpV5lng7VSQy5jrcxAwS5pINv3rad0/YTl/i6HWMHQZGNp6AgxMz1
# lWvN+AJpCb0espxHgRo+qLlon6V8WqGwXWrG9Pq//XmK/k9NMqyxZ9eq601C51c5
# Fu5S8l1hKLrL82J7pdxzwkKKEEuC2NRwSk8k0n7Rl+emYDs+0ZPnrL23K/jYy7wQ
# cu13qJoJLsNRf1K7u5WfQEfhEG6YNqbwh0mqzEEB239Rlz4ZQ0x8JHrJEYs+Yz40
# 69Vs/3/vQmceaL7UxdECAwEAAaOCATYwggEyMB0GA1UdDgQWBBTS3wjZLC5lrSBh
# LImLhCqa0c10sjAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNV
# HR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2Ny
# bC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
# KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAy
# MDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMIMA0G
# CSqGSIb3DQEBCwUAA4ICAQCvYAsQuCFW2ClUARz+c7SXP5H4Erm3C+YU0XlRNbsE
# lSqfdkn3fyCLxYBkHMFZQGXPA7mzoU7IZUdn0hXyuvrFM6DDrn/SLShe5t+PPkqW
# eOeYiEw8k4BI6l4U5k07wX8hBwOoMRxs1aOe/JNkLHO6krl5j6/GZHrkTRzTsRUU
# Jp1FpnUzixiZWyavc0x/imG5yWdrSuccE9ndoq7Qbu1Pxa7swsUm5zNNMunaWGXD
# FAnS7s8RxJ1/P3qTtZ0Ja6VE6SeoHpdj7/hPuKJLXV/M89GNFn8HUDmVW5+YK/8D
# y7yKHHiiSd+ugAN+pW3PA6OYek0ryW1QKzbrW4P9SXAk+U5faXjBJoitW98+ZERW
# X387VHvaTWJ4Yo5BmkJ0U27Aal2ggi5j1PYuDxB3DsofM+7ebc4zgJ0GF4u6DQW0
# V4rc/F2zytl2rDQfUGlPtNUymUZVbWJbFqw64je8QsAnMeG1J8ohxjYlea3iLAzG
# wime4dbMSyEHoObVvzIN0d9BJ84xVeXKvET176GhY/PS6RTJZiW5PPihZh88F3Je
# cEvhlct/FbpQPt+mhDOBQAyqjI1tdBQlBFVX85xWd1JRnUkuxqshXqFwcxKr8GiF
# sb9AV7y7TT30fmMTs3gmnojFQt3MdD5Q3M/gBf1TdlhyiPNXTgJhP6iyZHfxKZi2
# czCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQEL
# BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNV
# BAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEwMB4X
# DTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMCVVMxEzAR
# BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
# Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
# bXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk4aZM
# 57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25PhdgM/9cT8dm
# 95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzB
# RMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6GnszrYBb
# fowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCO
# Mcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50ZuyjLVwIYw
# XE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW
# /aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0lBw0gg/w
# EPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1qGFphAXPK
# Z6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ+QuJYfM2
# BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PAPBXbGjfH
# CBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJKwYB
# BAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxGNSnPEP8v
# BO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYM
# KwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0
# LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEF
# BQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBW
# BgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUH
# AQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtp
# L2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG9w0BAQsF
# AAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U518Jx
# Nj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmCVgADsAW+
# iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2
# pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wMnosZiefw
# C2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7
# T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2dY3RILLFO
# Ry3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxnGSgkujhL
# mm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+CrvsQWY9af3L
# wUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokLjzbaukz5
# m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL6Xu/OHBE
# 0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggLLMIICNAIB
# ATCB+KGB0KSBzTCByjELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEmMCQGA1UE
# CxMdVGhhbGVzIFRTUyBFU046QUUyQy1FMzJCLTFBRkMxJTAjBgNVBAMTHE1pY3Jv
# c29mdCBUaW1lLVN0YW1wIFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVAND6JppVWWnb
# irQx4Ic7QWQ35lb+oIGDMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTAwDQYJKoZIhvcNAQEFBQACBQDmZ78wMCIYDzIwMjIwNjMwMTQyMDMyWhgPMjAy
# MjA3MDExNDIwMzJaMHQwOgYKKwYBBAGEWQoEATEsMCowCgIFAOZnvzACAQAwBwIB
# AAICJAEwBwIBAAICEdswCgIFAOZpELACAQAwNgYKKwYBBAGEWQoEAjEoMCYwDAYK
# KwYBBAGEWQoDAqAKMAgCAQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQUF
# AAOBgQCSf3MWz4ad0lGJwocdJ7vjKlHuhVenhlO8mZTsXZ9703BKpJGEdalKWWU9
# MmtUhTiVWEQ0tD4VHRJj5Q04XCmTdbOmQC92kcYSqOWWf9SLvuxQASTciAebBL73
# /zCzJKH/0Z+72DWxMXPonoCtQ/votoxg95DRxGGMMv0RQFsNOjGCBA0wggQJAgEB
# MIGTMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAABlklbYuEv3fdP
# AAEAAAGWMA0GCWCGSAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZIhvcN
# AQkQAQQwLwYJKoZIhvcNAQkEMSIEICJ4IDdna5sEgPDAuY/ng20mOSn1zTsBQ52d
# OFserNU2MIH6BgsqhkiG9w0BCRACLzGB6jCB5zCB5DCBvQQgdgTWAvgdNdOSdkcu
# gn52dCQPCX5WUEOrC6RyNy2yvZAwgZgwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEG
# A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
# cm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFt
# cCBQQ0EgMjAxMAITMwAAAZZJW2LhL933TwABAAABljAiBCDf+6vBy2k0w0Ss66ze
# kzM1seqejBLecqDTrRqUJl8tWjANBgkqhkiG9w0BAQsFAASCAgB1HCHyJWtLFzJl
# AvBH5NH6lDK5kKBG8bQAq+EzM/NdeW/8UUuqaG00h3wecC07QaDe6orwVJ00Re+l
# hDVdyUwK0+ltjUVcu7dacaTvi++pA9g92z4iTVGl8RbWbycfDwW1WiZw3LRS/pbB
# Rm8L50Slb3uX8Dm62iNqh0r/W52C1y/GZmppaxXG5BcfFLCWg1WU20SLLqbTvE+G
# XOeI8K70iHURCbQzSygB3t0/ZsTh0LwweCBhL9XApDBJutS6XgA/Rr88PAYWCcn5
# MQ8y7GBKQsVlFieTQNEVcAjjn0JQ0WXur7FCTxRdXyjn+3ut9CGgN4fOtYYm5Sno
# phyrRlTPcj8c4hIpLUkvuO3f7oLOue/CNPnlYVw6s7dM4i0s0vUI3LF3/9+vSRbX
# wzKBKrmDxWpQvYmFTjRrwgca9YPq7ZDwd/T4MOui976TQUi5YUXeMOGAp3uGseFQ
# GyWJDf2CiV4OjRuf6swEPhS2ftuUqnzgl77YPBjnoqMOqSRMw5tagQylvQFE1MtC
# s4PyeTtcR0XSH5Z6sCs7WyG0L7bUGQnx5NE1oEF8VLN71D9RfZ6WWDiA7O/OZ5aK
# SG1fINywlK1Y2AYP5ktUVW/00YBRB5byf+2WhSEKV+Lz45mqRB+p7ZVFlH88R/jX
# QCclXgZc7CW3t4KDbhL9uY1K9DS25w==
# SIG # End signature block
